### ISSUE TITLE
Rasm ko'proq ichkariga kirib ketibdi lineka bn qarab to'g'rilab qo'ysak bo'ladi

### ISSUE THREAD

**Issue by Azamatjon0110** [mashhurbek2005/bookmark#2]
![image](https://user-images.githubusercontent.com/105698184/176834465-828637a3-1afe-4138-9dc3-6483911a368e.png)

**Comment by mashhurbek2005** [comment]
Kotta rahmat. To'g'rilab qo'ydim 👍
